// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm5fpArowoibvuigEQG8RSO7-NoqmurIY',
    appId: '1:1083943258514:web:c97af01fe11f7b3b47194b',
    messagingSenderId: '1083943258514',
    projectId: 'insiit-production',
    authDomain: 'insiit-production.firebaseapp.com',
    storageBucket: 'insiit-production.appspot.com',
    measurementId: 'G-Q3WJM1D1E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI7fZEKHJ3sqxYTIRyCrpX9cpV6f8OXkg',
    appId: '1:1083943258514:android:1256252a7357527347194b',
    messagingSenderId: '1083943258514',
    projectId: 'insiit-production',
    storageBucket: 'insiit-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCotc330vJ2noxKRSMp5vsLi7vn3INx5I',
    appId: '1:1083943258514:ios:99b2469c9b14d1f447194b',
    messagingSenderId: '1083943258514',
    projectId: 'insiit-production',
    storageBucket: 'insiit-production.appspot.com',
    iosBundleId: 'com.example.insiit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCotc330vJ2noxKRSMp5vsLi7vn3INx5I',
    appId: '1:1083943258514:ios:c6b1b824efbc508447194b',
    messagingSenderId: '1083943258514',
    projectId: 'insiit-production',
    storageBucket: 'insiit-production.appspot.com',
    iosBundleId: 'com.example.insiit.RunnerTests',
  );
}
