// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpene2UfOIDy4WVn5G9lMkxsPl1twRd70',
    appId: '1:313416279537:web:095d63e8835f4d1607d050',
    messagingSenderId: '313416279537',
    projectId: 'notifyinsiit',
    authDomain: 'notifyinsiit.firebaseapp.com',
    storageBucket: 'notifyinsiit.appspot.com',
    measurementId: 'G-R4HPEGHK08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrRLbXc6_wV33akm2CeTkk7rLo6i4vxDU',
    appId: '1:313416279537:android:f1a579cc5fa1a90f07d050',
    messagingSenderId: '313416279537',
    projectId: 'notifyinsiit',
    storageBucket: 'notifyinsiit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmD5xyk42UiFdoSdtGwGhOomKs5ulmsZI',
    appId: '1:313416279537:ios:1dd1ebf2cf45e04407d050',
    messagingSenderId: '313416279537',
    projectId: 'notifyinsiit',
    storageBucket: 'notifyinsiit.appspot.com',
    androidClientId: '313416279537-7qtqp95mfbi3gavc3pedq7id1gbm3f4l.apps.googleusercontent.com',
    iosClientId: '313416279537-tvq5a98v51ds6mba6plo2ai5l522s3j4.apps.googleusercontent.com',
    iosBundleId: 'com.example.insiit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmD5xyk42UiFdoSdtGwGhOomKs5ulmsZI',
    appId: '1:313416279537:ios:58d4f86552ec728407d050',
    messagingSenderId: '313416279537',
    projectId: 'notifyinsiit',
    storageBucket: 'notifyinsiit.appspot.com',
    androidClientId: '313416279537-7qtqp95mfbi3gavc3pedq7id1gbm3f4l.apps.googleusercontent.com',
    iosClientId: '313416279537-3b99t51jkiteq7kiknj9hdlpdu6sqqu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.insiit.RunnerTests',
  );
}
